version: '3'

services:

  dashboard:
    build: ./frontend

    container_name: simnet-dashboard

    ports:
      - "4000:80"

    restart: always

  backend:
    build: ./backend

    container_name: simnet-backend

    ports:
      - "5000:5000"

    restart: always

  db:
    image: postgres:15

    container_name: simnet-db

    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: simnet

    ports:
      - "5432:5432"

    restart: always